---
# Create Consul configuration
- name: CONSUL | Create settings-file
  become: true
  notify:
    - restart_consul
  copy:
    content: "{{ config_consul | to_nice_json }}"
    dest: '/etc/consul.d/consul.json'
    owner: "{{ consul_user | default('consul')}}"
    group: "{{ consul_group | default('consul') }}"
    mode: '0755'
  when: consul_install

# Create Consul configuration
- name: VAULT | Create settings-file
  become: true
  notify:
    - restart_vault
  copy:
    content: "{{ config_vault | to_nice_json }}"
    dest: '/etc/vault.d/vault.json'
    owner: "{{ vault_user | default('vault')}}"
    group: "{{ vault_group | default('vault') }}"
    mode: '0755'
  when: vault_install

# Create Consul configuration
- name: NOMAD | Create settings-file
  become: true
  notify:
    - restart_nomad
  copy:
    content: "{{ config_nomad | to_nice_json }}"
    dest: '/etc/nomad.d/nomad.json'
    owner: "{{ nomad_user | default('nomad')}}"
    group: "{{ nomad_group | default('nomad') }}"
    mode: '0755'
  when: nomad_install