---

  # Adding pre-required packages
- name: CENTOS | Add required OS packages
  become: true
  yum:
    name: yum-utils
    state: present

  # Adding HashiCorp official repository
- name: CENTOS | Add HashiCorp official repository
  become: yes
  get_url:
    url: "https://rpm.releases.hashicorp.com/{{ release }}/hashicorp.repo"
    dest: /etc/yum.repos.d/HashiCorp.repo
    mode: '0644'
  vars:
    release: RHEL

  # Install Consul package
- name: CENTOS | Install Consul package ({{ consul.version | default('latest') }})
  become: true
  yum:
    name: consul{{ consul.version | default('') }}
    update_cache: true
    state: present
  when: not consul.skip_install

  # Install Vault package
- name: CENTOS | Install Vault package ({{ vault.version | default('latest') }})
  become: true
  yum:
    name: vault{{ vault.version | default('') }}
    update_cache: true
    state: present
  when: not vault.skip_install

# Install Nomad package
- name: CENTOS | Install Nomad package ({{ nomad.version | default('latest') }})
  become: true
  yum:
    name: nomad{{ nomad.version | default('') }}
    update_cache: true
    state: present
  when: not nomad.skip_install