---

  # Modify the default service definition / systemd unit
- name: CONSUL | Update Systemd Unit file
  become: true
  notify:
    - reload_daemon
  lineinfile:
    path: /usr/lib/systemd/system/consul.service
    backup: true
    regexp: '^ExecStart='
    line: ExecStart=/usr/bin/consul agent -config-file=/etc/consul.d/consul.json
    owner: root
    group: root
    mode: '0440'
  when: not consul.skip_install

  # Modify the default service definition / systemd unit
- name: VAULT | Update Systemd Unit file
  become: true
  notify:
    - reload_daemon
  lineinfile:
    path: /usr/lib/systemd/system/vault.service
    backup: true
    regexp: '^ExecStart='
    line: ExecStart=/usr/bin/vault server -config=/etc/vault.d/vault.json
    owner: root
    group: root
    mode: '0440'
  when: not vault.skip_install

  # Modify the default service definition / systemd unit
- name: NOMAD | Update Systemd Unit file
  become: true
  notify:
    - reload_daemon
  lineinfile:
    path: /usr/lib/systemd/system/nomad.service
    backup: true
    regexp: '^ExecStart='
    line: ExecStart=/usr/bin/nomad agent -config /etc/nomad.d/nomad.json
    owner: root
    group: root
    mode: '0440'
  when: not nomad.skip_install

- name: Systemd unit definitions modified
  meta: flush_handlers
