# DOCS:
#   - https://github.com/ansible-community/molecule
#   - https://molecule.readthedocs.io/en/latest/
---
name: Molecule for Ansible Role Testing
description: Ansible Role Testing with Molecule

inputs:
  molecule-command:
    description: The [molecule]("https://molecule.readthedocs.io/en/latest/") command to execute
    required: false
    default: list

runs:
  # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-actions
  using: docker
  image: Dockerfile
  args: ["molecule","${{ inputs.molecule-command }}"]

# https://haya14busa.github.io/github-action-brandings/
branding:
  icon: check
  color: green
