# DOCS:
#   - https://github.com/ansible-community/molecule
#   - https://molecule.readthedocs.io/en/latest/
---
name: Molecule for Ansible Role Testing
description: Ansible Role Testing with Molecule

inputs:
  image-name:
    description: The os image name (passed to molecule scenario)
    required: false
    default: centos
  image-tag:
    description: The os image tag (passed to molecule scenario)
    required: false
    default: latest
  image-command:
    description: The os image command (passed to molecule scenario)
    required: false
    default: /usr/sbin/init
  molecule-command:
    description: The [molecule]("https://molecule.readthedocs.io/en/latest/") command to execute
    required: false
    default: list

runs:
  # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-actions
  using: docker
  image: quay.io/ansible/molecule:3.0.7
  entrypoint: /bin/sh
  args: ["-c","cd ${GITHUB_REPOSITORY}; molecule ${{ inputs.molecule-command }}"]
  env:
    PLATFORM_IMAGE: "${{ inputs.image-name }}:${{ inputs.image-tag }}"
    PLATFORM_IMAGE_CMD: "${{ inputs.image-command }}"

# https://haya14busa.github.io/github-action-brandings/
branding:
  icon: check
  color: green
