# DOCS:
#   - https://github.com/ansible-community/molecule
#   - https://molecule.readthedocs.io/en/latest/
---
name: Molecule for Ansible Role Testing
description: Ansible Role Testing with Molecule

inputs:
  molecule_workdir:
    description: The [molecule]("https://molecule.readthedocs.io/en/latest/") working directory
    required: false
    default: '${GITHUB_REPOSITORY}'
  molecule_command:
    description: The [molecule]("https://molecule.readthedocs.io/en/latest/") command to execute
    required: false
    default: list
  molecule_scenario:
    description: The [molecule]("https://molecule.readthedocs.io/en/latest/") scenario to use
    required: false
    default: default

runs:
  using: docker
  image: quay.io/ansible/molecule:3.0.6 # latest
  env:
    MLC_WORKDIR: 
    MLC_COMMAND: ${{ inputs.molecule_command }}
    MLC_SCENARIO: ${{ inputs.molecule_scenario }}
  entrypoint: /bin/sh
  args:
    - "-c"
    - "/usr/bin/molecule ${MLC_COMMAND} -s ${MLC_SCENARIO}"

# https://haya14busa.github.io/github-action-brandings/
branding:
  icon: check
  color: green