# INFO:
#   This is a playbook to execute after image is created,
#   but before testing role
---

- name: Verify
  hosts: all
  tasks:

    - name: REDHAT | OS Preparation
      block:
        - name: PREPARE | Install packages
          package:
            name:
              - sudo
              - iproute
            state: present
      when: ansible_os_family == "RedHat"

    - name: DEBIAN | OS Preparation
      block:
        - name: PREPARE | Update apt-cache
          apt:
            update_cache: true
            cache_valid_time: 600
      when: ansible_os_family == 'Debian'
