# INFO:
#   This is a playbook with tests to execute after
#   the role is applied to image
---

- name: VERIFY
  hosts: all

  pre_tasks:

    - name: VERIFY | Add CENTOS packages
      become: true
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - epel-release
      when: ansible_distribution | lower == 'centos'

    - name: VERIFY | Add common packages
      become: true
      package:
        name: "{{ item }}"
        state: present
      loop:
        - jq

  tasks:

    - name: VERIFY CONSUL | Running scripts..
      script:
        cmd: "{{ item }}"
      register: script_output_consul
      loop:
        - ../scripts/consul-check.sh

    - name: VERIFY VAULT | Running scripts..
      script:
        cmd: "{{ item }}"
      register: script_output_vault
      loop:
        - ../scripts/vault-init.sh
        - ../scripts/vault-check.sh

    - name: VERIFY NOMAD | Running scripts..
      script:
        cmd: "{{ item }}"
      register: script_output_nomad
      loop:
        - ../scripts/nomad-check.sh

    - debug:
        var: script_output_consul.results[0].stdout_lines

    - debug:
        var: script_output_vault.results[0].stdout_lines

    - debug:
        var: script_output_nomad.results[0].stdout_lines
