---
dependency:
  name: galaxy

driver:
  name: docker

provisioner:
  name: ansible
  log: false
  env:
    CUSTOM_INFO: centos-8
  playbooks:
    #create: '../resources/playbooks/create.yml'
    #prepare: '../resources/playbooks/prepare.yml'
    converge: '../_resources/playbooks/converge.yml'
    verify:   '../_resources/playbooks/verify.yml'
    #destroy: '../resources/playbooks/destroy.yml'
    #cleanup: '../resources/playbooks/cleanup.yml'

verifier:
  name: testinfra # ansible
  enabled: false
  directory: ../_resources/tests/
  env:
    FOO: bar

platforms:
  - name: mlc-hashicluster-centos
    image: centos:8
    command: /usr/sbin/init
    privileged: true
    security_opts:
      - seccomp=unconfined
    environment:
      container: docker
    published_ports:
      - 0.0.0.0:8200:8200/tcp
      - 0.0.0.0:8500:8500/tcp
      - 0.0.0.0:4646:4646/tcp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /run
    tty: true
