---
name: 'example action'
description: 'just for testing'

inputs:
  greeting:
    required: true
    default: 'Hello'
  who-to-greet:
    required: true
    default: 'World'

outputs:
  result:
    description: Resulting string
    value: "{{ inputs.greeting }}, {{ who-inputs.to-greet }}"

runs:
  using: "composite"
  steps:
    - run: echo "{{ outputs.result.description }} is {{ outputs.result }}"
      shell: bash