---
scenario:
  name: default

dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: "mlc-default"
    image: "${PLATFORM_IMAGE:-'centos:latest'}"
    command: "${PLATFORM_IMAGE_CMD:-'/usr/sbin/init'}"
    pre_build_image: true
    environment:
      container: docker
    privileged: true
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - '/tmp'
      - '/run'
      - '/run/lock'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tty: true

provisioner:
  name: ansible
  log: true
  env:
    CREATOR: kreditorforeningen
  playbooks:
    #create: '../resources/playbooks/create.yml'
    prepare:  '../_resources/playbooks/prepare.yml'
    converge: '../_resources/playbooks/converge.yml'
    verify:   '../_resources/playbooks/verify.yml'
    #destroy: '../resources/playbooks/destroy.yml'
    #cleanup: '../resources/playbooks/cleanup.yml'

verifier:
  name: ansible
