---
dependency:
  name: galaxy

driver:
  name: docker

provisioner:
  name: ansible
  log: true
  env:
    CUSTOM_INFO: ubuntu-1804
  playbooks:
    #create:  '../_resources/playbooks/create.yml'
    prepare:  '../_resources/playbooks/prepare.yml'
    converge: '../_resources/playbooks/converge.yml'
    verify:   '../_resources/playbooks/verify.yml'
    #destroy: '../_resources/playbooks/destroy.yml'
    #cleanup: '../_resources/playbooks/cleanup.yml'

verifier:
  name: ansible
  enabled: true

platforms:
  - name: 'mlc-hashicluster-ubuntu'
    image: 'geerlingguy/docker-ubuntu2004-ansible' #'ubuntu:18.04'
    command: '/sbin/init'
    privileged: true
    security_opts:
      - seccomp=unconfined
    environment:
      container: docker
    #published_ports:
    #  - '0.0.0.0:8200:8200/tcp'
    #  - '0.0.0.0:8500:8500/tcp'
    #  - '0.0.0.0:4646:4646/tcp'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    tmpfs:
      - '/tmp'
      - '/run'
      - '/run/lock'
    #  - '/sys/fs/cgroup'
    #  - '/var/lib/journal'
    tty: true
