---
dependency:
  name: galaxy

driver:
  name: docker

provisioner:
  name: ansible
  log: true
  env:
    CUSTOM_INFO: ubuntu-1804
  playbooks:
    #create: '../resources/playbooks/create.yml'
    #prepare: '../resources/playbooks/prepare.yml'
    converge: '../_resources/playbooks/converge.yml'
    verify:   '../_resources/playbooks/verify.yml'
    #destroy: '../resources/playbooks/destroy.yml'
    #cleanup: '../resources/playbooks/cleanup.yml'

verifier:
  name: ansible
  enabled: true

platforms:
  - name: 'mlc-hashicluster-ubuntu'
    image: 'geerlingguy/docker-ubuntu1804-ansible' #'ubuntu:18.04'
    privileged: true
    security_opts:
      - seccomp=unconfined
    command: '/sbin/init'
    environment:
      container: docker
    published_ports:
      - '0.0.0.0:8200:8200/tcp'
      - '0.0.0.0:8500:8500/tcp'
      - '0.0.0.0:4646:4646/tcp'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - '/tmp'
      - '/run'
    tty: true
