---
name: Molecule
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  molecule-test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      max-parallel: 0
      fail-fast: true
      matrix:
        os:
          - centos-7
          - centos-8
          - ubuntu-18.04
          - ubuntu-20.04
        include:
          - os: centos-7
            NAME: centos
            TAG: '7'
            COMMAND: /usr/sbin/init
          - os: centos-8
            NAME: centos
            TAG: '8'
            COMMAND: /usr/sbin/init
          - os: ubuntu-18.04
            NAME: dokken/ubuntu-18.04
            TAG: 'latest'
            COMMAND: /lib/systemd/systemd
          - os: ubuntu-20.04
            NAME: dokken/ubuntu-20.04
            TAG: 'latest'
            COMMAND: /lib/systemd/systemd

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: local actions at root
        run: "ln -fs ${GITHUB_REPOSITORY}/.github/actions ./actions"

      - name: molecule
        uses: ./actions/molecule
        with:
          image-name: "${{ matrix.NAME }}"
          image-tag: "${{ matrix.TAG }}"
          image-command: "${{ matrix.COMMAND }}"
          molecule-command: 'test'
